BEGIN TRANSACTION;
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات آنالیز قرضه و ژئو تکنیک بخش كهک قم', 'سازمان آب منطقه ای قم');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک اداره تعاون رباط كریم', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان سالن تشریح شهرستان كرج', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان بخشداري كرج', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان ستاد بحران تهران', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مخزن 5000 مترمکعبي تهرانسر', 'شركت آب و فاضلاب غرب تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات مکانیک خاک توسعه كارخانه آرد سیبلي آستارا', 'شركت سيبلي استارا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات تحلیل پایداری ترانشه هاي مجاور مخزن نمک زدائي گچساران', 'شركت توسعه صنايع نفت و انرژی قشم');
INSERT INTO geotechnical_projects (project, employer) VALUES ('انجام عملیات حفاري ژئوتکنیک و آزمایشات صحرایي در پروژه مخازن LNG', 'موسسه مهندسين مشاور ساحل(قرارگاه خاتم)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک زمین مجاور بانک پاسارگاددر میدان باستاني شعار رشت', 'شركت گسترش فن آوران ساخت');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک و مهندسي پي فاز یک 3000 واحدي پیشواي ورامین', 'شركت ساختماني دبله');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک طرح مسکن مهر علویجه نجف آباد اصفهان', 'بنياد مسكن انقلاب اسلامي استان اصفهان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک و كنترل كیفي مصالح (سهامي خاص)- پروژه گردشگري لاهیج', 'شركت توسعه گردشگری ايران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک ساختمان پزشکي قانوني جنوب تهران', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک 600 واحدي بنفشه فاز 0 اندیشه', 'شركت سرمايه گذاری مسكن تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک خیابان میرداماد تهران', 'شركت ليزينگ بانک پاسارگاد');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک سایت سیلوي زردانه اسد اباد', 'شركت زردانه');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک مجتمع تجاري اداري خیابان میرداماد تهران', 'شركت ساختماني معلم (بنياد مستضعفان)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مجتمع تجاري و اداري خیابان پاسداران تهران', 'شركت ساختماني معلم (بنياد مستضعفان)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک سیلوي اشتهارد', 'شركت فدک');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات مکانیک خاک ساختمان جدید بانک پاسارگاد شعبه مطهري رشت', 'شركت فن آوران ساخت');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات مکانیک خاک هتل چهار ستاره 5 طبقه – خیابان شیخ زاهد گیلاني', 'شركت گردشگری ايران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات مکانیک خاک هتل رستوران نگین تاج گیلان', 'شركت نگين تاج');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات مکانیک خاک توسعه كارخانه آرد آذر گندم شهر صنعتي رشت', 'شركت آرد آذر كندم');
INSERT INTO geotechnical_projects (project, employer) VALUES ('حفاري اكتشافي پروژه توسعه ساختمانهاي آموزشیدانشگاه آزاد آستارا- آستارا', 'دانشگاه آزاد آستارا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('حفاري اكتشافي پروژه توسعه دانشگاه آزاد تنکابن', 'دانشگاه آزاد تنكابن');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات مکانیک خاک 960 واحدي ایلام', 'اتحاديه مسكن مهر كارمندان ايلام');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه توسعه سیلوي شهرک صنعتي لوشان', 'شركت آهن وفولاد لوشان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه دانشکده شیمي', 'دانشگاه تربيت معلم خوارزمي كرج');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه دانشکده روانشناسي تربیتي', 'دانشگاه تربيت معلم خوارزمي كرج');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه ارغوان بندر انزلي', 'صندوق مسكن جوانان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه ساختمان اداري شركت سالار شیمي', 'شركت سالار شيمي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک طرح 99 ساله اراضي ضیاء آباد اسلامشهر', 'اتحاديه تعاوني های مسكن اسلامشهر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک پروژه ساختمان اداره امور مالیاتي كرج', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات میکرو گراني سنجي ساختمان پزشکي قانوني جنوب تهران', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات لرزه شناسي درون چاهي مجتمع تجاري امام واوان', 'شركت آريا سازه سازان پارس');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كارخانه M D F شهرک صنعتي لوشان', 'آهن و فولاد لوشان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک برج مسکوني 24 طبقه طاووس منطقه آزادتجاري انزلي', 'مديريت برج طاووس');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مخزن 15000 مترمکعبي منطقه 22 تهران', 'شركت آب و فاضلاب غرب تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مخزن 5000 مترمکعبي شاهدشهر', 'شركت آب و فاضلاب غرب تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک بیمارستان دهگلان', 'سازمان مسكن وشهرسازی كردستان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مخازن 5000 و 2000 صفادشت', 'شركت آب و فاضلاب غرب تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک سایت بازیافت منطقه 18 تهران', 'سازمان مديريت پسماند شهرداری تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع مسکوني 315 واحدي سبحان', 'آسيب های اجتماعي شهرداری تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع هاي مسکوني یاس 1 و 2 تهران', 'خدمات موتوری شهرداری تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مخزن 5000 مترمکعبي امیریه شهریار', 'شركت آب و فاضلاب غرب تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كتابخانه عمومي خیر آباد ورامین', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كتابخانه عمومي طارند ورامین', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كتابخانه عمومي قیامدشت', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان اداره كار فیروزكوه', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان بهزیستي نسیم شهر', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان توانبخشي گلستان رباط كریم', 'سازمان مسكن و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('دكل مخابراتي جنگل ابر شاهرود', 'مخابرات شركت نفت');
INSERT INTO geotechnical_projects (project, employer) VALUES ('دكل مخابراتي بندرعباس', 'مخابرات شركت نفت');
INSERT INTO geotechnical_projects (project, employer) VALUES ('دكل مخابراتي رفسنجان', 'مخابرات شركت نفت');
INSERT INTO geotechnical_projects (project, employer) VALUES ('دكل مخابراتي مراغه', 'مخابرات شركت نفت');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک نیروگاه گازي عنبرآباد جیرفت', 'سازمان توسعه برق ايران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع تجاري هلال احمر رشت', 'شركت سرمايه گذاری هلال احمر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک سالن ورزشي معلولین و جانبازان سمنان', 'وزارت ورزش و جوانان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک برج 40طبقه نگین فرمانیه', 'شركت ساختماني معلم (بنياد مستضعفان)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک برج 40 طبقه نگین میرداماد', 'شركت ساختماني معلم (بنياد مستضعفان)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک برج 30 طبقه نگین جنت آباد', 'شركت ساختماني معلم (بنياد مستضعفان)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک 500 واحدي فاز 2 شهرجدید پردیس', 'شركت سامان سازان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک برج هاي 17 طبقه كوهستان رودهن', 'شركت سامان سازان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع تجاري خیابان طالقاني تهران', 'شركت سرمايه گذاری هلال احمر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک 1700 واحدي فاز 2 شهر جدید هشتگرد', 'شركت تعاوني خاوران سازه');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک 5000 واحدي مسکن مهر اسلامشهر', 'تعاوني های مسكن مهر اسلامشهر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک حوزه علمیه امام محمد تقي )ع( قلهک تهران', 'موسسه تحقيقات زلزله آريا(شهرداری تهران)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک شهر كتاب و زورخانه جماران تهران', 'موسسه تحقيقات زلزله آريا(شهرداری تهران)');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک ساختمان برق پالایشگاه نفت تهران', 'شركت پالايش و پخش فراورده های نفتي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک توسعه كتابخانه ، موزه و مركز اسناد مجلس', 'مجلس شورای اسلامي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو فیزیک كتابخانه ، موزه و مركز اسناد مجلس', 'مجلس شورای اسلامي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پادگان ولیعصر زنجان', 'نيروی هوائي سپاه پاسداران انقلاب اسلامي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كارخانه روغن كشي شهر صنعتي شمس آباد', 'موسسه چراغچي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع آموزشي رزمندگان اسلام كرمانشاه', 'موسسه رزمندگان اسلام');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک بافت فرسوده خیابان مولوي تهران', 'مطالعات ژئوتکنیک بافت فرسوده خیابان مولوي تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک بیمارستان امیر اعلم تهران', 'شركت مشاور جم');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک طرح مقاوم سازي ادارات گاز استان گیلان', 'شركت گاز استان گيلان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان اقامتي راهور شهرک آزمایش تهران', 'ناجا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک اداره ثبت احوال پردیس', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع فرهنگي و هنري شهرري', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک موزه كرمانشاه', 'اداره كل ميراث فرهنگي ، صنايع دستي كرمانشاه');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان منابع طبیعي و ابخیزداري پردیس', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک بیمارستان 350 تختخوابي شهید مفتح ورامین', 'شركت مادر تخصصي تجيزات پزشكي');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک خط انتقال اب و مخازن سایت گهر زمین سیرجان', 'شركت سنگ آهن گهر زمين');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع فرهنگي و هنري پیشوا', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک فرهنگسراي شهریار', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كتابخانه شهرستان بهارستان', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پست برق 62 GIS غرب رشت', 'شركت برق منطقه ای گيلان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان دیسپاچینگ برق تهران', 'شركت برق منطقه ای تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک و ژئوالکتریک پست برق 400كیلوولت منطقه 22 تهران', 'شركت برق منطقه ای تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه دانشکده پلیس بین الملل ناجا', 'ناجا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه احداث مركز جامع سلامت گلشهر', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه احداث ساختمانهاي مسکوني 11 طبقه ساعس ناجا', 'ناجا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک طرحهاي شركت آب و فاضلاب جنوب غربي استان تهران', 'آب و فاضلاب جنوب غربي استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک احداث خط 2 گندلهسازي سایت گهر زمین سیرجان', 'شركت سنگ آهن گهر زمين');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک احداث ساختمانهاي جدید سایت گهرزمین سیرجان', 'شركت سنگ آهن گهر زمين');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک احداث ساختمان مسکوني 14 طبقه سیرجان', 'شركت تعاوني مسكن كارگران توسعه آهن و فولاد گل گهر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک احداث ساختمان واقع در فاز 3 پارک فناوري پردیس', 'شركت فرآورده بافت ايرانيان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه اداري رفاهي سایت مطهري بانک سپه', 'بانک سپه');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مركز امداد جاده اي ملارد', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مركز امداد جاده اي ورامین', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مركز بهداشت ظهیر آباد شهرري', 'اداره كل راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پروژه هاي ورزشي استان تهران', 'اداره كل ورزش و جوانان استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مسجد بین راهي گل گهر', 'شركت مديريت و عمران گل گهر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک فرودگاه شهید آریافر شهرري', 'ناجا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات زئوتکنیک ساختمان رادار هواشناسي گنبد كاووس', 'اداره كل هواشناسي استان گلستان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع خیابان بخارست تهران', 'كارگزاری بانک صادرات ايران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئو تکنیک مجتمع صنعتي شهرک صنعتي گرمسار', 'شركت پارسوا');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک طرح نوسعه گندله سازي سایت بردسیر', 'شركت سنگ آهن گهر زمين');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كارخانه باتري لیتیوم یون پرند', 'شركت مپنا - ميدكو');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان اداري شوراي نگهبان قانون اساسي', '-');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ساختمان مجتمع پزشكي قانوني شهرقدس', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كارخانه احیا ء مشیر بردسیر', 'شركت فكور صنعت تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كلانتري امر آباد ورامین', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک كتابخانه دماوند', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک مجتمع تجاري خاریس', 'شهرداری گرمسار');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ثبت احوال مركزي تهران', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک فرهنگسراي قرچک', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک ثبت احوال ملارد', 'اداره راه و شهرسازی استان تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پست برق پرنیان رباط كریم', 'شركت برق منطقه ای تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پست برق شهید عراقي تهران', 'شركت برق منطقه ای تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پست برق 400 شهرک صنعتي گل گهر', 'شركت پارسيان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک دكل هاي انتقال برق شهرک صنعتي گل گهر', 'شركت توسعه ،عمران و مديريت منطقه گل گهر');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مخازن انتقال آب فولاد غدیر ني ریز', 'شركت جهاد نصر كرمان');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پست برق 400 اشتهارد', 'شركت برق منطقه ای تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('دانشکده فناوري هاي نوین پزشکي', 'دانشگاه علوم پزشكي تهران');
INSERT INTO geotechnical_projects (project, employer) VALUES ('مطالعات ژئوتکنیک پست برق صفائیه 2', 'شركت برق منطقه ای تهران');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه پست برق 400 نیروگاه سمنان', 'شركت فرانيرو');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي برجهاي طاووس منطقه آزاد كاسپین', 'منطقه ازاد انزلي');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي مجتمع تجاري و اداري امام واوان', 'شركت آريا سازه');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي كتابخانه مركزي دانشگاه تربیت معلم كرج', 'دانشگاه تربيت معلم');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي 5000 واحدي مسکن مهر اسلامشهر', 'تعاوني مسكن مهر');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي آسفالت نیروگاه سمنان', 'شركت مپنا- توسعه');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي پروژه 700 واحدي هشتگرد', 'شركت اتحاد عمران پارس');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي دانشکده روانشناسي دانشگاه تربیت معلم كرج', 'دانشگاه تربيت معلم خوارزمي');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي پروژه مسکن مهر 1400 واحدي شهریار', 'تعاوني مسكن مهر');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي مركز بازیافت كهریزک', 'سازمان پسماند شهرداری تهران');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي نیروگاه شاهرود', 'سازمان توسعه برق ايران');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي دانشگاه آزاد قیامدشت', 'دانشگاه آزاد اسلامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('مجتمع دیباجي تهران', 'شركت ساختماني معلم');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي 1500و 2020 واحدي منطقه 22 تهران', 'نيروی هوائي سپاه');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي پست برق 63 گهرزمین سیرجان', 'شركت گهر زمين');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه پست برق 400 نیروگاه شهید كاظمي سیرجان', 'شركت پارسيان');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي گندله سازي گهر زمین سیرجان', 'شركت سنگ آهن گهر زمين');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه پست برق 230 كارخانه كنستانتره شهرک بیجار', 'شركت صبانور');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي ساحل شرقي كانال كردان', 'شركت آب منطقه ای استان تهران');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه 500 واحدي ورد آورد', 'شركت آريان پاسارگاد(وابسته به بانک پاسارگاد)');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه خیابان میرداماد تهران', 'شركت آريان پاسارگاد(وابسته به بانک پاسارگاد)');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه 500 واحدي هشتگرد', 'تعاوني مسكن خبر نگاران');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه 1000 واحدي ملارد', 'تعاوني مسكن صابرين ارتش');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه هاي رز، لاله هاي 1و 2و 3 ، بنفشه', 'شركت توليد مسكن خاور');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي ورزشگاه غدیر دانشگاه ناجا', 'نيروی انتظامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي دكل هاي مخابراتي', 'شركت صنايع مخابراتي شرق');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پادگان كمیل', 'سپاه پاسداران انقلاب اسلامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پادگان نبوت', 'سپاه پاسداران انقلاب اسلامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پادگان مدرس', 'سپاه پاسداران انقلاب اسلامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پاسگاههاي مرزباني ناجا', 'نيروی انتظامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي بلوكهاي سازماني زیبادشت تهران', 'نيروی انتظامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي طرح انتقال آب به جنوب شرق كشور', 'شرکت انتقال آب خليج فارس');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرارآزمایشگاه كنترل كیفي نیروگاه سمنگان سیرجان', 'شرکت نيروگاهي كرمانيان');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرارآزمایشگاه كنترل كیفي نیروگاه سیکل تركیبي كاشان', 'شرکت مپنا- توسعه1');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي كلید خانه پست برق نیروگاه شهید كاظمي سیرجان', 'شرکت پارسيان');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پست برق 400 جهان فولاد سیرجان', 'شرکت پارسيان');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پست برق 230 هشتگرد', 'شرکت برق تهران');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پست برق حسن آباد كرج', 'شرکت برق تهران');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه محلي تقاطع هاي غیر همسطح شهر كرمان', 'شهرداری كرمان');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه 0میلیون تن كنستانتره سنگ آهن گهرزمین', 'شرکت مهندسي فكور صنعت');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات كنترل كیفي پروژه كارخانه كنستانتره گهر زمین', 'شرکت مهندسي فكور صنعت');
INSERT INTO quality_control_projects (project, employer) VALUES ('پارکینگ و حسینیه فاتب', 'نيروی انتظامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('پژوهشگاه علوم انتظامي و مطالعات اجتماعي', 'نيروی انتظامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('اقامت گاه شهرک آزمایش راهور ناجا', 'نيروی انتظامي');
INSERT INTO quality_control_projects (project, employer) VALUES ('پست برق ادارات مركزي بانک ملي', 'بانک ملي');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرارآزمایشگاه كنترل كیفي نیروگاه سیکل تركیبي سبزوار', 'شرکت مپنا – توسعه 1');
INSERT INTO quality_control_projects (project, employer) VALUES ('خدمات آزمایشگاهي ژئوتکنیک و مقاومت مصالح شهر جدید اند', 'شرکت عمران شهر جديد انديشه');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرار آزمایشگاه هاي كنترل كیفي منطقه گل گهر سیرجان', 'شرکت توسعه، عمران و مديريت گل گهر');
INSERT INTO quality_control_projects (project, employer) VALUES ('پروژه بازیابي آب برگشتي از سد باطله گهر زمین', 'شرکت فلات پارس');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرار آزمایشگاه پروژه پارک آبي گل گهر', 'شرکت نظم آوران معدن و صنعت گلگهر');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرار آزمایشگاه كنترل كیفي نیروگاه اسلام اباد اصفهان', 'شرکت مپنا-توسعه 1');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرار آزمایشگاه پروژه پارک آبي گل گهر', 'شرکت گهر پارک سيرجان');
INSERT INTO quality_control_projects (project, employer) VALUES ('استقرار آزمایشگاه تاسیسات جانبي گهر زمین سیرجان', 'شرکت سنگ آهن گل گهر');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي تقاطع هاي غیر همسطح پارک گردشگري', 'شرکت توسعه، عمران و مديريت گل گهر');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي نیروگاه فتوولتائیک آفتاب شرق', 'شرکت مپنا – توسعه 3');
INSERT INTO quality_control_projects (project, employer) VALUES ('آزمایشگاه كنترل كیفي نیروگاه شهرري', 'شرکت مپنا – توسعه 1');
COMMIT;
